[workspace]
authors = ["bethac07 <bcimini@broadinstitute.org>"]
channels = ["conda-forge"]
name = "zarr-testing-2026-hackathon"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
marimo = ">=0.23.4,<0.24"
virtualizarr = ">=2.6.0,<3"
aiohttp = ">=3.13.5,<4"

[pypi-dependencies]
vizarr = { git = "https://github.com/hms-dbmi/vizarr.git", subdirectory = "python" }
